<?php

namespace Troiswa\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * News2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class News2Repository extends EntityRepository
{
}
