<?php

namespace Troiswa\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordRepository extends EntityRepository
{
}
