imports:
    - { resource: parameters.yml }
    #- { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

security:
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: form[_username]
                password_parameter: form[_password]
            logout:
                path: /logout
                target: /news/
            #http_basic:
            #    realm: "Accès restreint"
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control: 
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        #in_memory:
        #    memory:
        #        users:
        #            john: { password: john, roles: "ROLE_USER" }
        #            admin: { password: admin, roles: "ROLE_ADMIN" }
        administrators:
            entity: { class: TroiswaTestBundle:User, property: username }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Troiswa\TestBundle\Entity\User: 
            algorithm: pbkdf2
            hash_algorithm: sha512
            encode_as_base64: true
            iterations: 1000
